name: Auto Merge, Build, and Deploy to Docker Hub

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
  schedule:
    - cron: '05 15 * * *'  # 매일 00:05 (KST 기준)
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge_build_deploy:
    if: github.ref == 'refs/heads/dev'  # dev 브랜치에서만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

      - name: Check for new commits in feat/* branches
        id: check_commits
        run: |
          git fetch --all
          # 병합되지 않은 feat/* 브랜치 찾기
          TARGET_BRANCHES=$(git branch -r --no-merged origin/dev | grep 'origin/feat/' | sed 's|origin/||')
          if [ -z "$TARGET_BRANCHES" ]; then
            echo "No feat/* branches to process."
            echo "has_new_commits=false" >> $GITHUB_ENV
          else
            echo "Target branches: $TARGET_BRANCHES"
            echo "has_new_commits=true" >> $GITHUB_ENV
          fi

      - name: Create or Merge PRs from feat/* branches to dev
        if: env.has_new_commits == 'true'
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git fetch --all
          git branch -r --no-merged origin/dev | grep 'origin/feat/' | sed 's|origin/||' | while read -r TARGET_BRANCH; do
            DIFF_COUNT=$(git rev-list --count "origin/$TARGET_BRANCH" --not origin/dev)
            if [ "$DIFF_COUNT" -eq 0 ]; then
              echo "No new commits in $TARGET_BRANCH; skipping PR creation."
              continue
            fi
            PR_URL=$(gh pr list --base dev --head "$TARGET_BRANCH" --json url --jq '.[0].url' || echo "")
            if [ -z "$PR_URL" ]; then
              PR_URL=$(gh pr create --base dev --head "$TARGET_BRANCH" --title "Auto merge $TARGET_BRANCH into dev" --body "자동 생성된 Pull Request")
            fi
            echo "Attempting to merge $PR_URL"
            gh pr merge "$PR_URL" --squash --delete-branch --auto || echo "Merge failed for $TARGET_BRANCH"
          done

      - name: Log in to Docker Hub
        if: env.has_new_commits == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        if: env.has_new_commits == 'true'
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev
          export DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest
          docker build -f dockerfile.local -t $DOCKER_TAG . \
            --build-arg REACT_APP_KAKAO_CLIENT_ID=${{ secrets.REACT_APP_KAKAO_CLIENT_ID }} \
            --build-arg REACT_APP_KAKAO_AUTH_CODE_PATH=${{ secrets.REACT_APP_KAKAO_AUTH_CODE_PATH }} \
            --build-arg REACT_APP_KAKAO_REDIRECT_URI=${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }} \
            --build-arg REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} \
            --build-arg REACT_APP_GOOGLE_AUTH_CODE_PATH=${{ secrets.REACT_APP_GOOGLE_AUTH_CODE_PATH }} \
            --build-arg REACT_APP_GOOGLE_REDIRECT_URI=${{ secrets.REACT_APP_GOOGLE_REDIRECT_URI }} \
            --build-arg REACT_APP_GITHUB_CLIENT_ID=${{ secrets.REACT_APP_GITHUB_CLIENT_ID }} \
            --build-arg REACT_APP_GITHUB_AUTH_CODE_PATH=${{ secrets.REACT_APP_GITHUB_AUTH_CODE_PATH }} \
            --build-arg REACT_APP_URI=${{ secrets.REACT_APP_LOCAL_URI }} \
            --build-arg REACT_APP_SPRING_URI=${{ secrets.REACT_APP_SPRING_LOCAL_URI }} \
            --build-arg REACT_APP_ML_URI=${{ secrets.REACT_APP_ML_LOCAL_URI }}
          docker push $DOCKER_TAG

  deploy_local:
    runs-on: self-hosted
    needs: auto_merge_build_deploy
    if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true' && github.ref == 'refs/heads/dev'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Stop and remove existing container
        shell: powershell
        run: |
          $containers = docker ps -q --filter "name=narrativa_front"
          if ($containers) {
            docker stop $containers
            docker rm $containers
          }

      - name: Remove old Docker image
        shell: powershell
        run: |
          $images = docker images --filter "reference=${{ secrets.DOCKER_USERNAME }}/narrativa_front" -q
          if ($images) {
            docker rmi $images
          }

      - name: Pull new Docker image
        shell: powershell
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest

      - name: Run new Docker container
        shell: powershell
        run: |
          docker run -d --name narrativa_front `
            -p 3010:3010 `
            -e "REACT_APP_KAKAO_CLIENT_ID=${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}" `
            -e "REACT_APP_KAKAO_AUTH_CODE_PATH=${{ secrets.REACT_APP_KAKAO_AUTH_CODE_PATH }}" `
            -e "REACT_APP_KAKAO_REDIRECT_URI=${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }}" `
            -e "REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}" `
            -e "REACT_APP_GOOGLE_AUTH_CODE_PATH=${{ secrets.REACT_APP_GOOGLE_AUTH_CODE_PATH }}" `
            -e "REACT_APP_GOOGLE_REDIRECT_URI=${{ secrets.REACT_APP_GOOGLE_REDIRECT_URI }}" `
            -e "REACT_APP_GITHUB_CLIENT_ID=${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}" `
            -e "REACT_APP_GITHUB_AUTH_CODE_PATH=${{ secrets.REACT_APP_GITHUB_AUTH_CODE_PATH }}" `
            -e "REACT_APP_URI=${{ secrets.REACT_APP_LOCAL_URI }}" `
            -e "REACT_APP_SPRING_URI=${{ secrets.REACT_APP_SPRING_LOCAL_URI }}" `
            -e "REACT_APP_ML_URI=${{ secrets.REACT_APP_ML_LOCAL_URI }}" `
            ${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest

      - name: Verify environment variables in container
        shell: powershell
        run: |
          docker exec narrativa_front printenv > container_env.log
          if ! docker exec narrativa_front printenv | findstr "REACT_APP_KAKAO_CLIENT_ID=${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}"; then
            exit 1
          fi
          echo "All environment variables verified successfully!"
