deploy_local:
  runs-on: self-hosted
  needs: auto_merge_build_deploy
  if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true' && github.ref == 'refs/heads/dev'
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Stop and remove existing container
      shell: powershell
      run: |
        $containers = docker ps -q --filter "name=narrativa_front"
        if ($containers) {
          docker stop $containers
          docker rm $containers
        }

    - name: Remove old Docker image
      shell: powershell
      run: |
        $images = docker images --filter "reference=${{ secrets.DOCKER_USERNAME }}/narrativa_front" -q
        if ($images) {
          docker rmi $images
        }

    - name: Pull new Docker image
      shell: powershell
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest

    - name: Run new Docker container
      shell: powershell
      run: |
        docker run -d --name narrativa_front `
          -p 3010:3010 `
          -e REACT_APP_KAKAO_CLIENT_ID=${{ secrets.REACT_APP_KAKAO_CLIENT_ID }} `
          -e REACT_APP_KAKAO_AUTH_CODE_PATH=${{ secrets.REACT_APP_KAKAO_AUTH_CODE_PATH }} `
          -e REACT_APP_KAKAO_REDIRECT_URI=${{ secrets.REACT_APP_KAKAO_REDIRECT_URI_PART }} `
          -e REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} `
          -e REACT_APP_GOOGLE_AUTH_CODE_PATH=${{ secrets.REACT_APP_GOOGLE_AUTH_CODE_PATH }} `
          -e REACT_APP_GOOGLE_REDIRECT_URI=${{ secrets.REACT_APP_GOOGLE_REDIRECT_URI_PART }} `
          -e REACT_APP_GITHUB_CLIENT_ID=${{ secrets.REACT_APP_GITHUB_CLIENT_ID }} `
          -e REACT_APP_GITHUB_AUTH_CODE_PATH=${{ secrets.REACT_APP_GITHUB_AUTH_CODE_PATH }} `
          -e REACT_APP_LOCAL_URI=${{ secrets.REACT_APP_LOCAL_URI }} `
          -e REACT_APP_SPRING_LOCAL_URI=${{ secrets.REACT_APP_SPRING_LOCAL_URI }} `
          -e REACT_APP_ML_LOCAL_URI=${{ secrets.REACT_APP_ML_LOCAL_URI }} `
          ${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest
